app/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.admin.sites import JavaScriptCatalog
from django.urls import include, path, re_path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from core.views import robots_txt, sitemap_index, sitemap_section
from search import views as search_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("aristarx/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("reviews/", include("reviews.urls"), name="reviews"),
    path("select2/", include("django_select2.urls")),
    path("accounts/", include("allauth.urls")),
    path("robots.txt", robots_txt, name="robots_txt"),
    path("sitemap.xml", sitemap_index, name="sitemap-index"),
    # Секции по языкам и типам страниц
    # Пример: /sitemaps/en/catalog_organizations/sitemap-1.xml
    re_path(
        r"^sitemaps/(?P<lang>[a-z]{2})/(?P<section>[\w_]+)/sitemap-(?P<num>\d+)\.xml$",
        sitemap_section,
        name="sitemap-section",
    ),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()


if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += i18n_patterns(
        path("rosetta/", include("rosetta.urls")), prefix_default_language=False
    )

urlpatterns += i18n_patterns(
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("search/", search_views.search, name="search"),
    path("catalog/", include("catalog.urls"), name="catalog"),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include(wagtail_urls)),
    prefix_default_language=False,
)

reviews/urls.py
from django.urls import path

from reviews import views

app_name = "reviews"

urlpatterns = [
    path("add/", views.add_review, name="add_review"),
]

reviews/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from wagtail.admin.panels import FieldPanel, MultipleChooserPanel
from wagtail.models import ClusterableModel, Orderable, ParentalKey

from core.utils import starsort

USER_MODEL = get_user_model()


class ReviewStatus(models.TextChoices):
    MODERATION = "moderation", _("Moderation")
    PUBLISHED = "published", _("Published")
    REJECTED = "rejected", _("Rejected")
    DELETED = "deleted", _("Deleted")


class Review(ClusterableModel):
    user = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE,
        related_name="reviews",
    )

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    status = models.CharField(
        max_length=20,
        choices=ReviewStatus.choices,
        default=ReviewStatus.MODERATION,
    )

    rating = models.PositiveIntegerField(
        verbose_name=_("Rating"),
        help_text=_("Rating value"),
    )

    comment = models.TextField(
        verbose_name=_("Comment"),
        help_text=_("Comment text"),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
        help_text=_("Creation date and time"),
    )
    go_live_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Go live at"),
        help_text=_("Date and time when the review will be published"),
    )

    panels = [
        FieldPanel("user", read_only=True),
        "status",
        "rating",
        "comment",
        "go_live_at",
        MultipleChooserPanel(
            "images",
            heading=_("Images"),
            chooser_field_name="image",
        ),
    ]

    def __str__(self):
        return f"{self.user}"


class ReviewImage(Orderable):
    review = ParentalKey(
        "reviews.Review",
        on_delete=models.CASCADE,
        related_name="images",
    )
    image = models.ForeignKey(
        "wagtailimages.Image",
        on_delete=models.CASCADE,
        related_name="+",
        verbose_name=_("Image"),
    )

    panels = [
        FieldPanel("image"),
    ]

    class Meta(Orderable.Meta):
        verbose_name = _("Image")
        verbose_name_plural = _("Images")


@receiver(post_save, sender=Review)
def update_organization_rating_after_add_review(sender, instance, *args, **kwargs):
    update_avg_rating(sender, instance, **kwargs)
    update_rating_score(sender, instance, *args, **kwargs)


@receiver(post_delete, sender=Review)
def update_organization_rating_after_delete_review(sender, instance, *args, **kwargs):
    update_avg_rating(sender, instance, **kwargs)
    update_rating_score(sender, instance, *args, **kwargs)


def update_avg_rating(sender, instance, **kwargs):
    """Update content_object avg_rating after Review save"""

    if instance.status == ReviewStatus.PUBLISHED:
        content_object = instance.content_object
        all_reviews = Review.objects.filter(
            content_type=ContentType.objects.get_for_model(content_object),
            object_id=content_object.pk,
            status=ReviewStatus.PUBLISHED,
        )
        avg_rating = all_reviews.aggregate(models.Avg("rating"))["rating__avg"]
        content_object.avg_rating = avg_rating
        content_object.save()


def update_rating_score(sender, instance, *args, **kwargs):
    obj = instance.content_object

    if not hasattr(obj, "avg_rating"):
        return

    obj_reviews = sender.objects.filter(
        status=ReviewStatus.PUBLISHED,
        object_id=obj.id,
        content_type=obj.content_type,
        # parent=None,
        rating__gte=0,
    )

    stars = (
        obj_reviews.filter(rating=5).count(),
        obj_reviews.filter(rating=4).count(),
        obj_reviews.filter(rating=3).count(),
        obj_reviews.filter(rating=2).count(),
        obj_reviews.filter(rating=1).count(),
    )

    obj.rating_score = float(starsort(stars))
    obj.save()

reviews/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, JsonResponse
from django.utils.translation import gettext_lazy as _
from wagtail.admin.ui.tables import StatusTagColumn, UserColumn
from wagtail.admin.viewsets.model import ModelViewSet
from wagtail.images.models import Image
from wagtail.models import ContentType

from core.utils import is_ajax
from reviews.models import Review, ReviewImage, ReviewStatus


class ReviewViewSet(ModelViewSet):
    model = Review
    icon = "glasses"
    menu_label = _("Reviews")
    add_to_admin_menu = True
    menu_order = 250
    list_display = (
        "id",
        UserColumn("user", label=_("User")),
        "content_type",
        "content_object",
        "rating",
        "status",
        StatusTagColumn(
            "status",
            lambda obj: obj.status == ReviewStatus.PUBLISHED,
            label=_("Status"),
        ),
    )


review_viewset = ReviewViewSet("reviews_list")


@login_required
def add_review(request):
    if not request.method == "POST" and not is_ajax(request):
        raise Http404

    images = request.FILES.getlist("images")
    comment = request.POST.get("comment")
    rating = int(request.POST.get("rating"))
    object_id = request.POST.get("object_id")

    try:
        content_type = request.POST.get("content_type")
        content_type = ContentType.objects.get(id=content_type)
    except ContentType.DoesNotExist:
        return JsonResponse(
            {"message": _("Invalid content type.")},
            status=400,
        )

    try:
        review = Review(
            user=request.user,
            content_type=content_type,
            object_id=object_id,
            rating=rating,
            comment=comment,
        )
        review.save()
    except Exception as e:
        return JsonResponse(
            {"message": _("Error saving review: %s" % str(e))},
            status=400,
        )

    if images:
        for image in images:
            if not image.name.endswith((".jpg", ".jpeg")):
                return JsonResponse(
                    {"error": _("Only .jpg and .jpeg files are allowed.")},
                    status=400,
                )
            if image.size > 2 * 1024 * 1024:
                return JsonResponse(
                    {"error": _("File size must be less than 2MB.")},
                    status=400,
                )
            wagtail_image = Image(
                title=f"[REVIEW] {request.user.username} - {review.content_object.title}",
                file=image,
                uploaded_by_user=request.user,
            )
            wagtail_image.save()
            review_image = ReviewImage(
                review=review,
                image=wagtail_image,
            )
            review_image.save()

    return JsonResponse(
        {
            "message": _(
                "Review submitted successfully. It will be published after admin approval."
            ),
        }
    )

reviews/templates/reviews/review.html
{% load i18n wagtailimages_tags core %}

<article class="review" id="review-{{ review.pk }}" itemprop="review" itemscope itemtype="https://schema.org/Review">
  <div class="review__header">
    <div class="review__avatar">
      {% with review.user.get_full_name|make_list|first|default:review.user|make_list|first as char %}<span data-char="{{ char|lower }}">{{ char }}</span>{% endwith %}
    </div>
    <div class="review__info">
      <div class="review__rating" itemprop="reviewRating" itemscope itemtype="https://schema.org/Rating">
        <meta itemprop="worstRating" content="1">
        <meta itemprop="bestRating" content="5">
        <meta itemprop="ratingValue" content="{{ review.rating }}">
        {% include "includes/stars-rating.html" with stars=review.rating %}
      </div>
      <div class="review__meta">
        <div class="review__date">
          <meta itemprop="datePublished" content="{{ review.created_at|date:'Y-m-d\TH:i:s' }}">
          {% now "Y" as current_year %}
          <time datetime="{{ review.created_at|date:'c' }}">
            {% if review.created_at|date:'Y' == current_year %}
              {{ review.created_at|date:'j E' }}
            {% else %}
              {% trans "This year" %}
            {% endif %}
          </time>
        </div>
        <div class="review__author" itemprop="author">{{ review.user.get_full_name|default:review.user }}</div>
      </div>
    </div>
  </div>
  <div class="review__content" itemprop="reviewBody">
    <p>
      {{ review.comment|striptags|replace:"\n|<br>" }}
    </p>
  </div>
  {% if review.images %}
    <div class="review__images">
      {% for review_image in review.images.all %}
        {% image review_image.image original as full_image %}
        <a href="{{ full_image.url }}" class="review__image" data-fancybox="review-{{ review.pk }}">{% picture review_image.image fill-100x100 loading="lazy" format-{avif,webp,jpeg} %}</a>
      {% endfor %}
    </div>
  {% endif %}
</article>

reviews/templates/reviews/reviews-form.html
{% load i18n %}

<form class="review-form" action="{% url 'reviews:add_review' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="hidden" name="object_id" value="{{ page.pk }}">
  <input type="hidden" name="content_type" value="{{ page.content_type.pk }}">

  <div class="review-form--left">
    <div class="review-form__field">
      <div class="review-form__rating-container">
        <div class="review-form__field-title">{% trans "Give a rating" %}</div>
        <div class="review-form__rating">
          <input type="radio" id="rating-5" name="rating" value="5" required class="sr-only">
          <label for="rating-5">{% include "icons/star.svg" %}</label>
          <input type="radio" id="rating-4" name="rating" value="4" class="sr-only">
          <label for="rating-4">{% include "icons/star.svg" %}</label>
          <input type="radio" id="rating-3" name="rating" value="3" class="sr-only">
          <label for="rating-3">{% include "icons/star.svg" %}</label>
          <input type="radio" id="rating-2" name="rating" value="2" class="sr-only">
          <label for="rating-2">{% include "icons/star.svg" %}</label>
          <input type="radio" id="rating-1" name="rating" value="1" class="sr-only">
          <label for="rating-1">{% include "icons/star.svg" %}</label>
        </div>
      </div>
    </div>

    <div class="review-form__field">
      <div class="review-form__comment">
        <textarea cols="40" rows="10" maxlength="1000" name="comment" placeholder="{% trans "What do you think?" %}" required></textarea>
      </div>
    </div>

    <button type="submit" class="btn sm">{% trans "Send" %}</button>
  </div>

  <div class="review-form--right">
    <div class="review-form__field">
      <div class="review-form__field-title">{% trans "Upload photos" %}</div>
      <div class="review-form__images-upload images-upload">
        <div class="images-upload__errors"></div>
        <label class="images-upload__info" for="images-input">
          <input type="file" name="images" id="images-input" accept="image/jpeg" multiple>
          <span>{% trans "Drag and drop images here or" %}&nbsp;</span>
          <span class="images-upload__info--browse">{% trans "click to upload" %}</span>
        </label>
        <div class="images-upload__preview"></div>
      </div>
    </div>
  </div>
</form>

reviews/templates/reviews/reviews-list.html
{% load reviews %}

{% get_reviews page as reviews %}

{% if reviews %}
  <ul class="reviews-list">
    {% for review in reviews %}
      <li class="reviews-list__item">{% include "reviews/review.html" %}</li>
    {% endfor %}
  </div>
{% endif %}

reviews/templates/reviews/reviews.html
{% load i18n reviews %}

{% get_reviews_count page as reviews_count %}

{% spaceless %}
  <div id="reviews" class="reviews">
    {% if not reviews_count %}
      <div class=" h3 reviews__title">{% trans "Be the first to leave a review" %}</div>
    {% else %}
      <div class=" h3 reviews__title">{% blocktrans count counter=reviews_count %}{{ counter }} review{% plural %}{{ counter }} reviews{% endblocktrans %}</div>
    {% endif %}

    {% include "reviews/reviews-form.html" %}

    {% include "reviews/reviews-list.html" %}
  </div>
{% endspaceless %}