app/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.admin.sites import JavaScriptCatalog
from django.urls import include, path, re_path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from core.views import robots_txt, sitemap_index, sitemap_section
from search import views as search_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("aristarx/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("reviews/", include("reviews.urls"), name="reviews"),
    path("select2/", include("django_select2.urls")),
    path("accounts/", include("allauth.urls")),
    path("robots.txt", robots_txt, name="robots_txt"),
    path("sitemap.xml", sitemap_index, name="sitemap-index"),
    # Секции по языкам и типам страниц
    # Пример: /sitemaps/en/catalog_organizations/sitemap-1.xml
    re_path(
        r"^sitemaps/(?P<lang>[a-z]{2})/(?P<section>[\w_]+)/sitemap-(?P<num>\d+)\.xml$",
        sitemap_section,
        name="sitemap-section",
    ),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()


if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += i18n_patterns(
        path("rosetta/", include("rosetta.urls")), prefix_default_language=False
    )

urlpatterns += i18n_patterns(
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("search/", search_views.search, name="search"),
    path("catalog/", include("catalog.urls"), name="catalog"),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include(wagtail_urls)),
    prefix_default_language=False,
)

comments/urls.py
from django.urls import path

from . import views

app_name = "comments"

urlpatterns = [
    path("add/", views.add_comment, name="add_comment"),
    path("header/", views.count_header, name="header"),
    path("delete/<int:comment_id>/", views.delete_comment, name="delete_comment"),
    path("publish/<int:comment_id>", views.publish_comment, name="publish_comment"),
    path("reject/<int:comment_id>", views.reject_comment, name="reject_comment"),
    path("delete/<int:comment_id>", views.delete_comment, name="delete_comment"),
]

comments/models.py
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from wagtail.admin.panels import FieldPanel, MultiFieldPanel, ObjectList, TabbedInterface

user_model = get_user_model()

COMMENT_PUBLISHED = 1
COMMENT_ON_MODERATION = 2
COMMENT_REJECTED = 3
COMMENT_DELETED = 4

COMMENT_STATUSES = (
    (COMMENT_PUBLISHED, _("Published")),
    (COMMENT_ON_MODERATION, _("On moderation")),
    (COMMENT_REJECTED, _("Rejected")),
    (COMMENT_DELETED, _("Deleted")),
)


class Comment(MPTTModel):
    parent = TreeForeignKey(
        "self",
        verbose_name=_("Parent"),
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="children",
    )

    user = models.ForeignKey(
        user_model, verbose_name=_("User"), on_delete=models.CASCADE
    )

    ip_address = models.GenericIPAddressField(
        verbose_name=_("IP address"), blank=True, null=True
    )

    created_at = models.DateTimeField(
        verbose_name=_("Created at"), auto_now=False, auto_now_add=True
    )
    status = models.IntegerField(verbose_name=_(
        "Status"), choices=COMMENT_STATUSES)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    comment = models.TextField(verbose_name=_("Comment text"))

    class MPTTMeta:
        order_insertion_by = ["-created_at"]

    class Meta(MPTTModel.Meta):
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")
        ordering = ["-created_at"]

    def __str__(self) -> str:
        end = "..." if len(self.comment) > 50 else ""  # type: ignore
        comment = self.comment[:50] + end  # type: ignore
        return mark_safe("%s: %s" % (self.user_name, escape(comment)))

    comment_panel = [
        MultiFieldPanel(
            [
                FieldPanel("status"),
                FieldPanel("comment", classname="readonly"),
            ],
            heading=_("Comment"),
        )
    ]

    user_panel = [
        MultiFieldPanel(
            [
                FieldPanel("ip_address", classname="readonly"),
            ],
            heading=_("User"),
        )
    ]

    object_panel = [
        MultiFieldPanel(
            [
                FieldPanel("content_type", classname="readonly"),
                FieldPanel("object_id", classname="readonly"),
            ],
            heading=_("Object"),
        )
    ]

    edit_handler = TabbedInterface(
        [
            ObjectList(comment_panel, heading=_("Comment")),
            ObjectList(user_panel, heading=_("User")),
            ObjectList(object_panel, heading=_("Object")),
        ]
    )

comments/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _

COMMENT_MAX_LENGTH = getattr(settings, 'COMMENT_MAX_LENGTH', 3000)


class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    parent_id = forms.IntegerField(widget=forms.HiddenInput)

    comment = forms.CharField(
        min_length=3,
        max_length=COMMENT_MAX_LENGTH,
        required=False,
        widget=forms.Textarea({
            'placeholder': _('Add comment ...'),
            'rows': 1
        })
    )

comments/views.py
import re

from django.apps import apps
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.html import strip_tags
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_GET, require_POST

from core.utils import is_ajax

from . import models
from .models import COMMENT_DELETED, COMMENT_ON_MODERATION, COMMENT_PUBLISHED, COMMENT_REJECTED
from .utils import check_for_bad_words

USER_MODEL = get_user_model()


@csrf_protect
@require_POST
@login_required
def add_comment(request):
    data = request.POST.copy()

    user = request.user

    ctype = data.get("content_type", None)
    object_id = data.get("object_id", None)

    next_url = data.get("next", None)

    if not ctype or not object_id:
        return HttpResponse(_("Hacker?"), status=403)  # type: ignore

    try:
        app_name, model_name = ctype.split(".")
        model = apps.get_model(app_name, model_name)
    except Exception:  # noqa
        return HttpResponse(_("Hacker?"), status=403)  # type: ignore

    try:
        target = model.objects.get(id=object_id)
    except model.DoesNotExist:
        return HttpResponse(_("Hacker?"), status=403)  # type: ignore

    content_type = ContentType.objects.get_for_model(model)

    parent = None
    parent_id = data.get("parent_id")

    comment = data.get("comment").strip()

    if len(comment) < 3:
        # type: ignore
        return HttpResponse(_("Comment is too short!"), status=403)

    status = (
        COMMENT_ON_MODERATION if check_for_bad_words(
            comment) else COMMENT_PUBLISHED
    )

    if parent_id:
        try:
            parent = models.Comment.objects.get(id=parent_id)
        except models.Comment.DoesNotExist:  # type: ignore
            return HttpResponse(_("Hacker?"), status=403)  # type: ignore

    x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")

    if x_forwarded_for:
        ip_address = x_forwarded_for.split(",")[0]
    else:
        ip_address = request.META.get("REMOTE_ADDR", None)

    comment = strip_tags(comment)
    comment = re.sub(r"[\n]{3,}", "\n\n", comment)

    new_comment = models.Comment(
        content_type=content_type,
        object_id=object_id,
        user=user,
        ip_address=ip_address,
        parent=parent,
        comment=comment,
        status=status,
    )

    new_comment.save()

    if is_ajax(request):
        if new_comment.status == COMMENT_PUBLISHED:
            template = "comments/comment_published.html"
        else:
            template = "comments/comment_on_moderation.html"

        return TemplateResponse(request, template, {"node": new_comment})

    if next_url:
        return redirect(next_url)

    return redirect(target.url)


@require_GET
def count_header(request):
    data = request.GET.copy()

    ctype = data.get("content_type", None)
    object_id = data.get("object_id", None)

    if not ctype or not object_id:
        raise Exception('"content_type" and "object_id" are required')

    app_name, model_name = ctype.split(".")
    model = apps.get_model(app_name, model_name)

    target = model.objects.get(id=object_id)

    return TemplateResponse(request, "comments/header.html", {"page": target})


@login_required
@permission_required("comments.can_edit")
def delete_comment(request, comment_id):
    comment = models.Comment.objects.get(id=comment_id)
    comment.status = COMMENT_DELETED
    comment.save()

    if is_ajax(request):
        return TemplateResponse(
            request, "comments/comment_deleted.html", {"node": comment}
        )

    try:
        back_url = request.META["HTTP_REFERER"]
    except Exception:  # noqa
        back_url = comment.content_object.url

    return redirect(back_url)


@login_required
@permission_required("comments.can_edit")
def reject_comment(request, comment_id):
    comment = models.Comment.objects.get(id=comment_id)
    comment.status = COMMENT_REJECTED
    comment.save()

    if is_ajax(request):
        return TemplateResponse(
            request, "comments/comment_deleted.html", {"node": comment}
        )

    try:
        back_url = request.META["HTTP_REFERER"]
    except Exception:  # noqa
        back_url = comment.content_object.url

    return redirect(back_url)


@login_required
@permission_required("comments.can_edit")
def publish_comment(request, comment_id):
    comment = models.Comment.objects.get(id=comment_id)
    comment.status = COMMENT_PUBLISHED
    comment.save()
    back_url = request.META["HTTP_REFERER"]
    return redirect(back_url)

comments/templates/comments/comment_deleted.html
{% load wagtailadmin_tags i18n comments %}

{% spaceless %}
  {% if request.user == node.user %}
    <li class="comments__comment comment deleted" id="comment-{{ node.id }}"{% if node.parent %} data-parent="comment-{{ node.parent.id }}"{% endif %}>
      <div class="comment__avatar">
        {% with node.user.get_short_name|default:node.user|make_list|first as char %}<span data-char="{{ char|lower }}">{{ char }}</span>{% endwith %}
      </div>
      <div class="comment__body">
        <div class="comment__info">
          <strong class="comment__user{% if request.user == node.user %} current{% endif %}{% if node.user.is_staff %} moderator-badge{% endif %}">{{ node.user.get_short_name|default:node.user }}</strong>
          <time class="comment__created_at">{{ node.created_at|timesince }} {% trans 'ago' %}</time>
        </div>
        <div class="comment__content">{% trans 'Comment was deleted by moderator' %}</div>
      </div>
    </li>
  {% endif %}
{% endspaceless %}

comments/templates/comments/comment_on_moderation.html
{% load wagtailadmin_tags i18n comments %}

{% spaceless %}
  {% if request.user == node.user %}
    <li class="comments__comment comment on-moderation" id="comment-{{ node.id }}"{% if node.parent %} data-parent="comment-{{ node.parent.id }}"{% endif %}>
      <div class="comment__avatar">
        {% with node.user.get_short_name|default:node.user|make_list|first as char %}<span data-char="{{ char|lower }}">{{ char }}</span>{% endwith %}
      </div>
      <div class="comment__body">
        <div class="comment__info">
          <strong class="comment__user{% if request.user == node.user %} current{% endif %}{% if node.user.is_staff %} moderator-badge{% endif %}">{{ node.user.get_short_name|default:node.user }}</strong>
          <time class="comment__created_at">{{ node.created_at|timesince }} {% trans 'ago' %}</time>
        </div>
        <div class="comment__content">{% trans 'The comment is under moderation' %}</div>
      </div>
    </li>
  {% endif %}
{% endspaceless %}

comments/templates/comments/comment_published.html
{% load wagtailadmin_tags i18n comments wagtailcore_tags core %}

{% spaceless %}
  <li class="comments__comment comment" id="comment-{{ node.id }}"{% if node.parent %} data-parent="comment-{{ node.parent.id }}"{% endif %}>
    <div class="comment__avatar">
      {% with node.user.get_short_name|default:node.user|make_list|first as char %}<span data-char="{{ char|lower }}">{{ char }}</span>{% endwith %}
    </div>
    <div class="comment__body">
      <div class="comment__info">
        <strong class="comment__user{% if request.user == node.user %} current{% endif %}{% if node.user.is_staff %} moderator-badge{% endif %}">{{ node.user.get_short_name|default:node.user }}</strong>
        <time class="comment__created_at">{{ node.created_at|date:'F, d l' }}</time>
      </div>
      <div class="comment__content">
        {{ node.comment|striptags|regex_replace:'\n|<br>'|richtext }}
      </div>
      <div class="comment__actions">
        <div class="comment__links">
          {% if request.user.is_authenticated and request.user != node.user %}
            <a href="?reply={{ node.id }}" class="comment__reply">{% trans 'Reply' %}</a>
          {% endif %}
          {% if perms.comments.can_edit %}
            <a href="{% url 'comments:delete_comment' comment_id=node.id %}" class="comment__delete">{% trans 'Delete' %}</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% if not node.is_leaf_node %}
      <ul class="comments__list--children">
        {{ children }}
      </ul>
    {% endif %}
  </li>
{% endspaceless %}

comments/templates/comments/comment_rejected.html
{% load wagtailadmin_tags i18n comments %}

{% spaceless %}
  {% if request.user == node.user %}
    <li class="comments__comment comment rejected" id="comment-{{ node.id }}"{% if node.parent %} data-parent="comment-{{ node.parent.id }}"{% endif %}>
      <div class="comment__avatar">
        {% with node.user.get_short_name|default:node.user|make_list|first as char %}<span data-char="{{ char|lower }}">{{ char }}</span>{% endwith %}
      </div>
      <div class="comment__body">
        <div class="comment__info">
          <strong class="comment__user{% if request.user == node.user %} current{% endif %}{% if node.user.is_staff %} moderator-badge{% endif %}">{{ node.user.get_short_name|default:node.user }}</strong>
          <time class="comment__created_at">{{ node.created_at|timesince }} {% trans 'ago' %}</time>
        </div>
        <div class="comment__content">{% trans 'The comment was rejected by the moderator' %}</div>
      </div>
    </li>
  {% endif %}
{% endspaceless %}

comments/templates/comments/comments_list.html
{% load mptt_tags %}
{% spaceless %}
	<ul class="comments__list">
		{% recursetree comments %}
			{% if node.status == COMMENT_PUBLISHED %}
				{% include 'comments/comment_published.html' %}
			{% elif node.status == COMMENT_ON_MODERATION %}
				{% include 'comments/comment_on_moderation.html' %}
			{% elif node.status == COMMENT_REJECTED %}
				{% include 'comments/comment_rejected.html' %}
			{% elif node.status == COMMENT_DELETED %}
				{% include 'comments/comment_deleted.html' %}
			{% endif %}
		{% endrecursetree %}
	</ul>
{% endspaceless %}

comments/templates/comments/form.html
{% load comments i18n socialaccount %}

{% spaceless %}
  {% include 'comments/header.html' %}
  {% if request.user.is_authenticated %}
    <form action="{% url 'comments:add_comment' %}" class="comments__form" method="post">
      {% csrf_token %}

      <input type="hidden" name="next" value="{{ request.path }}">

      {% for field in form %}
        {% if field.is_hidden %}
          {{ field }}
        {% else %}
          <div class="fields__group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
          </div>
        {% endif %}
      {% endfor %}

      <div class="form__actions">
        <a href="{{ request.path }}" class="cancel">{% trans 'Cancel' %}</a>
        <input type="submit" value="{% trans 'Send' %}" class="btn orange round">
      </div>

    </form>
  {% else %}
    <div class="text-center">
      <hr>
      <h4>{% trans 'Log in to leave a comment' %}</h4>

      {% with request.build_absolute_uri as next %}
        <form action="{% provider_login_url "google" openid="https://www.google.com/accounts/o8/id" next=next %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn text-icon">
            {% trans "Sign In" %}
            {% include "icons/login.svg" %}
          </button>
        </form>
      {% endwith %}
      <hr>
    </div>
  {% endif %}
{% endspaceless %}

comments/templates/comments/header.html
{% load comments i18n %}
{% get_comments_count page as comments_count %}
{% spaceless %}
	<div class="comments__header">
		<h3>
			{% blocktranslate count counter=comments_count %}{{ counter }} comment{% plural %}{{ counter }} comments{% endblocktranslate %}
		</h3>
	</div>
{% endspaceless %}