app/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.admin.sites import JavaScriptCatalog
from django.urls import include, path, re_path
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from core.views import robots_txt, sitemap_index, sitemap_section
from search import views as search_views

urlpatterns = [
    path("django-admin/", admin.site.urls),
    path("aristarx/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("reviews/", include("reviews.urls"), name="reviews"),
    path("select2/", include("django_select2.urls")),
    path("accounts/", include("allauth.urls")),
    path("robots.txt", robots_txt, name="robots_txt"),
    path("sitemap.xml", sitemap_index, name="sitemap-index"),
    # Секции по языкам и типам страниц
    # Пример: /sitemaps/en/catalog_organizations/sitemap-1.xml
    re_path(
        r"^sitemaps/(?P<lang>[a-z]{2})/(?P<section>[\w_]+)/sitemap-(?P<num>\d+)\.xml$",
        sitemap_section,
        name="sitemap-section",
    ),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()


if "rosetta" in settings.INSTALLED_APPS:
    urlpatterns += i18n_patterns(
        path("rosetta/", include("rosetta.urls")), prefix_default_language=False
    )

urlpatterns += i18n_patterns(
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("search/", search_views.search, name="search"),
    path("catalog/", include("catalog.urls"), name="catalog"),
    path("comments/", include("comments.urls", namespace="comments")),
    path("", include(wagtail_urls)),
    prefix_default_language=False,
)

catalog/urls.py
from django.urls import path

from .views import get_organizations_data, import_organization, organizations, search_cities

app_name = "catalog"
urlpatterns = [
    path("search-cities/", search_cities, name="search_cities"),
    path("organizations/", organizations, name="organizations"),
    path("import-organization/", import_organization, name="import_organization"),
    path(
        "get-organizations-data/", get_organizations_data, name="get_organizations_data"
    ),
]

catalog/views.py
import json
from functools import reduce

import django_filters
from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.db.models import F, OuterRef, Q, Subquery, Value
from django.db.models.functions import Coalesce, Concat, JSONObject
from django.http import Http404, JsonResponse
from django.shortcuts import render
from django.utils.html import strip_tags
from django.utils.translation import gettext_lazy as _
from wagtail.admin.filters import DateRangePickerWidget, WagtailFilterSet
from wagtail.admin.views.reports import PageReportView
from wagtail.admin.viewsets.base import ViewSetGroup
from wagtail.admin.viewsets.chooser import ChooserViewSet
from wagtail.admin.viewsets.model import ModelViewSet
from wagtail.admin.viewsets.pages import PageListingViewSet
from wagtail.images.models import Rendition

from catalog.models import (City, Language, Organization, OrganizationImage, OrganizationType, Reward, ServiceType,
                            ServiceTypeCategory)
from catalog.utils import get_start_end_day, to_12h
from core.models import SiteSettings
from core.utils import get_weekday_name, get_weekday_number, is_ajax, paginate


def search_cities(request):
    """Used for AJAX city search in header."""
    if request.method == "GET" and is_ajax(request):
        query = request.GET.get("q", "").strip().lower()
        cities = (
            City.objects.live().filter(title__istartswith=query).order_by("title")[:20]
        )
        cities = map(lambda city: {"url": city.url, "title": city.title}, cities)
        return JsonResponse(list(cities), safe=False)
    raise Http404


def organizations(request):
    """Organizations list page."""
    filters = {}

    allowed_filters = ["address"]

    # Check if request is GET and has query parameters
    if request.method == "GET":
        for key, value in request.GET.items():
            if key in allowed_filters:
                filters[key] = value
    else:
        raise Http404

    organizations = (
        Organization.objects.live()
        .filter(**filters)
        .order_by("-avg_rating", "-first_published_at")
    )

    organizations = paginate(request, organizations, 20)

    context = {"organizations": organizations}
    return render(request, "catalog/organizations.html", context)


class CityPageFilterSet(PageListingViewSet.filterset_class):  # type: ignore
    class Meta:
        model = City
        fields = ["popular"]


class CityPageListingViewSet(PageListingViewSet):
    model = City
    menu_label = _("Cities")
    add_to_admin_menu = False
    icon = "building-solid"
    filterset_class = CityPageFilterSet


class OrganizationTypePageListingViewSet(PageListingViewSet):
    model = OrganizationType
    menu_label = _("Organizations types")
    add_to_admin_menu = False
    icon = "store-solid"


class OrganizationPageListingViewSet(PageListingViewSet):
    model = Organization
    menu_label = _("Organizations")
    add_to_admin_menu = False
    icon = "briefcase-solid"


class ServiceTypeCategoryViewSet(ModelViewSet):
    model = ServiceTypeCategory
    menu_label = _("Service type categories")  # type: ignore
    add_to_admin_menu = False
    icon = "folder-open-inverse"
    search_fields = ["title"]  # type: ignore


class ServiceTypeCategoryChooserViewSet(ChooserViewSet):
    model = ServiceTypeCategory
    icon = "folder-open-inverse"
    choose_one_text = _("Choose a category")
    choose_another_text = _("Choose another category")
    edit_item_text = _("Edit this category")


service_type_category_chooser_viewset = ServiceTypeCategoryChooserViewSet(
    "catalog_service_type_category_chooser"
)


class ServiceTypeViewSet(ModelViewSet):
    model = ServiceType
    menu_label = _("Service types")  # type: ignore
    add_to_admin_menu = False
    icon = "tag"
    search_fields = ["name"]  # type: ignore


class LanguageViewSet(ModelViewSet):
    model = Language
    menu_label = _("Languages")  # type: ignore
    add_to_admin_menu = False
    icon = "globe"
    form_fields = ("language_name", "icon")


class RewardViewSet(ModelViewSet):
    model = Reward
    icon = "pick"  # type: ignore


class CatalogViewSetGroup(ViewSetGroup):
    menu_label = _("Catalog")
    menu_icon = "folder-open-inverse"
    items = (
        CityPageListingViewSet("catalog_city_pages"),
        OrganizationTypePageListingViewSet("catalog_organization_type_pages"),
        OrganizationPageListingViewSet("catalog_organization_pages"),
        ServiceTypeCategoryViewSet("catalog_service_type_categories"),
        ServiceTypeViewSet("catalog_service_types"),
        RewardViewSet("catalog_rewards"),
        LanguageViewSet("catalog_languages"),
    )
    menu_order = 100


@permission_required("catalog.add_organization")
def import_organization(request):
    if not request.method == "POST":
        raise Http404

    try:
        data = json.loads(request.body.decode("utf-8"))
    except json.JSONDecodeError:
        return JsonResponse({"message": "Invalid JSON"}, status=400)

    data_fields = data.keys()

    try:
        parent_id = data.get("parent_id")
        parent = OrganizationType.objects.get(id=int(parent_id))
    except (ValueError, OrganizationType.DoesNotExist):
        return JsonResponse(
            {"success": False, "message": "Invalid parent ID"}, status=400
        )

    # Check if Organization with this parent and legal name and address already exists
    legal_name = data.get("legal_name", "").strip()
    address = data.get("address_en", "").strip()
    if not legal_name:
        return JsonResponse(
            {"success": False, "message": "Legal name is required"}, status=400
        )
    if not address:
        return JsonResponse(
            {"success": False, "message": "AddressEn is required"}, status=400
        )
    if (
        Organization.objects.filter(
            legal_name__iexact=legal_name, address__iexact=address
        )
        .descendant_of(parent)
        .exists()
    ):
        return JsonResponse(
            {
                "success": False,
                "message": "Already exists!",
            },
            status=400,
        )

    awailable_fields = [
        "slug",
        "tin",
        "legal_name",
        "plus_code",
        "working_hours",
        "verified",
        "temporarily_closed",
        "languages",
        "ll",
        "show_on_map",
        "located_in",
        "service_types",
        "phones",
        "social_networks",
        "website_links",
    ]

    i18n_awailable_fields = [
        "title",
        "h1_title",
        "seo_title",
        "search_description",
        "description",
        "address",
        "how_to_arrive",
    ]

    awailable_locales = settings.MODELTRANSLATION_LANGUAGES

    for field in i18n_awailable_fields:
        for locale in awailable_locales:
            localized_field = f"{field}_{locale}"
            awailable_fields.append(localized_field)

    awailable_fields += i18n_awailable_fields

    new_organization = Organization()

    for field in data_fields:
        if field not in awailable_fields:
            continue

        # Get field type, ex: 'CharField', 'BooleanField', etc.
        field_type = new_organization._meta.get_field(field).get_internal_type()

        if field_type == "CharField":
            setattr(new_organization, field, data[field])
        elif field_type == "SlugField":
            slug = data[field].strip()
            if slug:
                setattr(new_organization, field, slug)
        elif (
            field_type == "TextField"
            and "search" not in field
            and "website" not in field
            and "social" not in field
        ):
            # Make paragraphs from text
            text = data[field].split("\n\n")
            text = "<p>" + "</p><p>".join(text) + "</p>"
            setattr(new_organization, field, text)
        elif field_type == "TextField":
            setattr(new_organization, field, data[field])
        elif field_type == "BooleanField":
            setattr(
                new_organization,
                field,
                data[field] in [True, "true", "True", 1, "yes", "on", "Yes", "On"],
            )
        elif field == "working_hours":
            if data[field]:
                wh = json.loads(data[field])
                days = []
                for day in wh:
                    if wh[day].lower() == "closed":
                        days.append(
                            {
                                "type": "day",
                                "value": {
                                    "day": get_weekday_number(day),
                                    "end": None,
                                    "start": None,
                                    "holiday": True,
                                    "last_client": False,
                                },
                            }
                        )
                    elif wh[day].lower() == "open 24 hours":
                        days.append(
                            {
                                "type": "day",
                                "value": {
                                    "day": get_weekday_number(day),
                                    "end": "23:59",
                                    "start": "00:00",
                                    "holiday": False,
                                    "last_client": False,
                                },
                            }
                        )
                    else:
                        try:
                            start, end = get_start_end_day(wh[day])
                        except ValueError:
                            return JsonResponse(
                                {
                                    "success": False,

catalog/templates/catalog/city_page.html
{% extends "base.html" %}

{% load wagtailcore_tags catalog %}

{% block content %}
	<div class="container">
		<h1 class="page__title">{{page.title}}</h1>
	</div>
  {% for block in page.content %}
    {% include_block block %}
  {% empty %}
    <section class="section section--latest-organizations">
      <div class="container">
        <div class="row v-gutters">
          {% get_paginated_organizations page as organizations %}
          {% for organization in organizations %}
            <div class="col-lg-3 col-sm-6 col-12">{% include "catalog/includes/organization-item.html" %}</div>
          {% endfor %}
        </div>
        {% include "includes/pagination.html" with page_obj=organizations %}
      </div>
    </section>
  {% endfor %}
{% endblock content %}

catalog/templates/catalog/organization_type_map.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}
  {{ page.title }} {% trans "on map" %}
{% endblock %}

{% block extrahead %}
  <meta name="description" content="{{ page.seo_title }} {% trans 'on map' %}">
{% endblock extrahead %}

{% block body_class %}template-organizations-map{% endblock %}

{% block content %}
  <div class="container fluid">
    <h1 class="page__title h2">{{ page.title }} {% trans "near me in" %} {{ page.get_parent.title }}</h1>
  </div>

  <div class="map-page">
    <div class="map-page__sidebar"></div>
    {% get_current_language as lang %}
    <div class="map-page__map" id="organizations-map" data-url="{% url 'catalog:get_organizations_data' %}" data-org-type-id="{{ page.id }}" data-ll="{{ page.get_parent.specific.ll|default:DEFAULT_LAT_LNG }}"></div>
  </div>
{% endblock content %}

{% block extra_js %}
  <script async src="https://maps.googleapis.com/maps/api/js?key={{ GOOGLE_MAPS_API_KEY }}&libraries=marker&region=GE&callback=initMap"></script>
{% endblock extra_js %}

catalog/templates/catalog/organization_type_page.html
{% extends "base.html" %}

{% load i18n wagtailcore_tags core catalog %}

{% block content %}
  <div class="container">
    <h1 class="page__title">{{ page.title|mark|safe }}</h1>
    {% if active_service_type %}
      <p>
        <big><strong>{% trans "By tag:" %}</strong></big> <mark>{{ active_service_type }}</mark>
      </p>
    {% endif %}
    <div class="page__description">{{ page.description|richtext }}</div>
  </div>

  <!-- TODO: rename `_top_organizations` to `top_organizations` -->
  {% get_top_organizations page as _top_organizations %}
  {% if top_organizations %}
    <section class="section section--top-organizations">
      <div class="container">
        {% trans "[[Top]] organizations" as section_title %}
        {% include "includes/section-header.html" %}

        <div class="row">
          <div class="swiper organizations-carousel">
            <div class="swiper-wrapper">
              {% for organization in top_organizations %}
                <div class="swiper-slide">{% include "catalog/includes/organization-item.html" %}</div>
              {% endfor %}
            </div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-button-next"></div>
          </div>
        </div>
      </div>
    </section>
  {% endif %}

  {% for block in page.content %}
    {% include_block block %}
  {% empty %}
    <section class="section section--latest-organizations">
      <div class="container">
        <div class="row v-gutters">
          {% get_paginated_organizations page as organizations %}
          {% for organization in organizations %}
            <div class="col-lg-3 col-sm-6 col-12">{% include "catalog/includes/organization-item.html" %}</div>
          {% endfor %}
        </div>
        {% include "includes/pagination.html" with page_obj=organizations %}
      </div>
    </section>
  {% endfor %}
{% endblock content %}

catalog/templates/catalog/organizations.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}
  {% trans "Organizations list" %}
{% endblock %}

{% block extrahead %}
  <meta name="description" content="{% trans "Organizations list page." %}">
  <link rel="canonical" href="{{ request.path }}" />
  <meta name="robots" content="noindex, follow">
{% endblock extrahead %}

{% block body_class %}template-catalog-organizations{% endblock %}

{% block content %}
  <section class="section section-new-in-city">
    <div class="container">
      {% if request.GET.address %}
        {% trans "[[By address]]: "|add:request.GET.address as section_title %}
      {% else %}
        {% trans "Organizations" as section_title %}
      {% endif %}
      {% include "includes/section-header.html" %}

      <div class="row v-gutters">
        {% for organization in organizations %}
          <div class="col-lg-3 col-sm-6 col-12">{% include "catalog/includes/organization-item.html" %}</div>
        {% endfor %}
      </div>

      {% include "includes/pagination.html" with page_obj=organizations %}
    </div>
  </section>
{% endblock content %}